/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codechallengewithjava8.api;

import static com.codechallengewithjava8.api.MessageUtils.getMessage;
import static com.codechallengewithjava8.service.StringUtils.join;
import static com.codechallengewithjava8.service.StringUtils.split;

import org.apache.commons.text.WordUtils;

import com.codechallengewithjava8.model.LinkedList;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
